# Generated by Django 5.2.8 on 2025-12-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsSplit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Oczekujący'), ('REJECTED', 'Odrzucony'), ('PAID', 'Sfinalizowany')], default='PENDING', max_length=10),
        ),
    ]
