# Generated by Django 5.2.8 on 2026-01-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EsSplit', '0006_loginlockout'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginlockout',
            new_name='EsSplit_log_ip_addr_9e5313_idx',
            old_name='EsSplit_log_ip_77a2f8_idx',
        ),
        migrations.RenameIndex(
            model_name='loginlockout',
            new_name='EsSplit_log_locked__533f33_idx',
            old_name='EsSplit_log_lo_4d1f0e_idx',
        ),
    ]
