# Generated by Django 5.0.6 on 2024-06-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsSplit', '0010_remove_bill_date_alter_bill_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.TextField(),
        ),
    ]
