# Generated by Django 5.2.8 on 2026-01-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsSplit', '0012_add_user_totp'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
