# Generated by Django 5.2.8 on 2026-01-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsSplit', '0013_add_avatar_to_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
